"""USER_ADD_UNIQUE

Revision ID: 019dabaa0eaa
Revises: 16c0d1cc379c
Create Date: 2022-10-24 19:03:47.188336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019dabaa0eaa'
down_revision = '16c0d1cc379c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account_user', ['id'])
    op.create_unique_constraint(None, 'account_user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_user', type_='unique')
    op.drop_constraint(None, 'account_user', type_='unique')
    # ### end Alembic commands ###
