"""ADD_COLUMN_IS_ADMIN

Revision ID: 16c0d1cc379c
Revises: de1e6ff6487d
Create Date: 2022-10-22 17:30:27.785956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c0d1cc379c'
down_revision = 'de1e6ff6487d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_user', 'is_admin')
    # ### end Alembic commands ###
