"""ADD_COLUMN_IS_BANNED

Revision ID: de1e6ff6487d
Revises: e1069340e405
Create Date: 2022-10-22 15:51:15.116865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1e6ff6487d'
down_revision = 'e1069340e405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_user', 'is_banned')
    # ### end Alembic commands ###
